### ISSUE TITLE
Update to latest actix-web version

### ISSUE THREAD

**Issue by newtack** [LukeMathWalker/tracing-actix-web#18]
Can you please update the crate to use actix-web version 4.0.0-beta.6?

Also, can you remove the following unnecessary dependencies from Cargo.toml (they are not directly used in the code)?
- actix-http
- actix-service

and unless you are dependent on very specific versions, can you update
tracing from "0.1.19" to "0.1", tracing-futures from "0.2.4" to "0.2", uuid from "0.8.1" to "0.8"?

This will make it easier to use this library when upgrading dependencies.

**Comment by LukeMathWalker** [comment]
> Can you please update the crate to use actix-web version 4.0.0-beta.6?

Error handling on beta.6 is in a half-broken state - see https://github.com/actix/actix-web/issues/2173 or https://github.com/LukeMathWalker/zero-to-production/issues/96
We will update to beta.7, when released, if the issue is fixed.

> Also, can you remove the following unnecessary dependencies from Cargo.toml (they are not directly used in the code)?
> 
>     * actix-http
> 
>     * actix-service

Those are necessary to get a "working" actix ecosystem, see issues above.

> and unless you are dependent on very specific versions, can you update
> tracing from "0.1.19" to "0.1", tracing-futures from "0.2.4" to "0.2", uuid from "0.8.1" to "0.8"?
> 
> This will make it easier to use this library when upgrading dependencies.

Asking for `0.1.19` in `Cargo.toml` means that any version `0.1.X` with `X >= 19` will work - you should have no problems at all updating your dependencies.
