### ISSUE TITLE
Ability to filter out tracing spans

### ISSUE THREAD

**Issue by lsunsi** [LukeMathWalker/tracing-actix-web#44]
Hi again!

First off, I love the current developments on the library. I've been using a private fork with some special features, but I've seen they were all implemented in upstream, so now I'm dropping the fork and getting back on track. Thanks for that!

The only thing I'm missing is the ability of filter out spans for specific requests (for example, I'm filtering out the /healthz tracings to avoid load on my exporter). Do you think this feature makes sense? If so, I imagine being able to return a Option<Span> on onRequestStart might do the trick. I could make a PR for this feature if it makes sense to you.

Anyway, congrats for the awesome work!

**Comment by LukeMathWalker** [comment]
Hey!
I see various ways to accomplish this without having to touch `tracing-actix-web`:

- Create a `debug` level span instead of an `info` level span when the route matches a certain path (i.e. this is how we do it in several codebases at my workplace);
- Use per-layer filters in `tracing` to match on properties like `http.endpoint` to filter out the span when exporting.
